### ISSUE TITLE
Board configuration causes crashes in engine (in dev mode)

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#229]
The following crashes the engine in dev mode 50% of the time.  I think it probably happened before I introduced same starting colour snake positions but will check on master.  Confirmed. This happens on master too.

![image](https://user-images.githubusercontent.com/1261268/52253081-a3e17280-28ba-11e9-829a-1f23dd78fca9.png)

Stacktrace
```
INFO[0080] controller rpc                                duration="19.641µs" method=/pb.Controller/ListGameFrames
INFO[0080] controller rpc                                duration="27.12µs" method=/pb.Controller/Status
INFO[0080] snake ate                                     Food="X:1 " Name=dedsnek SnakeID=a958b991-1f15-43aa-8c7f-696ef217b46b Turn=1
INFO[0080] snake ate                                     Food="X:2 Y:1 " Name=dedsnek SnakeID=e5850540-d9ce-404f-8099-959767722937 Turn=1
INFO[0080] snake ate                                     Food="Y:1 " Name=dedsnek SnakeID=c875c244-7dc0-489e-98c7-d81fa7600ee0 Turn=1
INFO[0080] controller rpc                                duration="21.858µs" method=/pb.Controller/ListGameFrames
panic: runtime error: makeslice: cap out of range

goroutine 67 [running]:
github.com/battlesnakeio/engine/rules.getUnoccupiedPoints(0x300000003, 0xc0004dd8a0, 0x4, 0x4, 0xc00021c140, 0x5, 0x8, 0x5, 0xc00073cb60, 0xc00021de80)
	/Users/user/go/src/github.com/battlesnakeio/engine/rules/tick.go:199 +0xc9
github.com/battlesnakeio/engine/rules.getUnoccupiedPoint(0x300000003, 0xc0004dd8a0, 0x4, 0x4, 0xc00021c140, 0x5, 0x8, 0x1)
	/Users/user/go/src/github.com/battlesnakeio/engine/rules/tick.go:154 +0x7a
github.com/battlesnakeio/engine/rules.updateFood(0xc000696280, 0xc00021de40, 0xc000515e40, 0x3, 0x4, 0x8, 0xc0000b8a00, 0x4, 0x4, 0xc00021dec0)
	/Users/user/go/src/github.com/battlesnakeio/engine/rules/tick.go:102 +0x2a5
github.com/battlesnakeio/engine/rules.GameTick(0xc000696280, 0xc00021de40, 0xc0006e8f00, 0xc000582470, 0x0)
	/Users/user/go/src/github.com/battlesnakeio/engine/rules/tick.go:59 +0x793
github.com/battlesnakeio/engine/worker.Runner(0x17f3f60, 0xc0006e8f00, 0x17f86c0, 0xc0000c0090, 0xc000528570, 0x24, 0x0, 0xc0003658c0)
	/Users/user/go/src/github.com/battlesnakeio/engine/worker/runner.go:48 +0x125
github.com/battlesnakeio/engine/worker.(*Worker).run(0xc000150b80, 0x17f3ea0, 0xc00007cb80, 0x7, 0x0, 0x0)
	/Users/user/go/src/github.com/battlesnakeio/engine/worker/worker.go:62 +0x25d
github.com/battlesnakeio/engine/worker.(*Worker).Run(0xc000150b80, 0x17f3ee0, 0xc0000b6040, 0x7)
	/Users/user/go/src/github.com/battlesnakeio/engine/worker/worker.go:28 +0x67
github.com/battlesnakeio/engine/cmd/engine/commands/server.glob..func8.2(0xc000150b80, 0x17f3ee0, 0xc0000b6040, 0xc0000b68e0, 0x7)
	/Users/user/go/src/github.com/battlesnakeio/engine/cmd/engine/commands/server/worker.go:101 +0xca
created by github.com/battlesnakeio/engine/cmd/engine/commands/server.glob..func8
	/Users/user/go/src/github.com/battlesnakeio/engine/cmd/engine/commands/server/worker.go:99 +0x21f
```

**Comment by dlsteuer** [comment]
Pretty sure this is because the board is so small, i think i have a fix for it.
