### ISSUE TITLE
Engine Crash

### ISSUE THREAD

**Issue by ColDog** [battlesnakeio/roadmap#256]
```
panic: runtime error: index out of range
​
goroutine 266 [running]:
github.com/battlesnakeio/engine/rules.getTournamentStartPoint(0x80000000b, 0xc0001d68c0, 0x8, 0x8, 0xc000036170)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/rules/create.go:91 +0x11f
github.com/battlesnakeio/engine/rules.getSnakes(0xc000320660, 0xc0004d5600, 0x14e172b, 0x17f5f60, 0x3, 0x3)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/rules/create.go:105 +0x64f
github.com/battlesnakeio/engine/rules.CreateInitialGame(0xc000320660, 0x1f84268, 0xc0004d56c0, 0x14d310d, 0xc0004d56a0, 0x1009973, 0x16bc460)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/rules/create.go:33 +0x40
github.com/battlesnakeio/engine/controller.(*Server).Create(0xc00000b8a0, 0x17fb7e0, 0xc000320630, 0xc000320660, 0xc00000b8a0, 0xc000320810, 0x3)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/controller/controller.go:111 +0x2f
github.com/battlesnakeio/engine/controller/pb._Controller_Create_Handler.func1(0x17fb7e0, 0xc000320630, 0x16f1700, 0xc000320660, 0x154e4a4, 0xc0001d6880, 0xc000320810, 0x3)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/controller/pb/controller.pb.go:1813 +0x86
github.com/battlesnakeio/engine/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x17fb7e0, 0xc000320630, 0x16f1700, 0xc000320660, 0x15, 0xc000326230, 0xc0004d57d8, 0x1048aaa)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x118
github.com/battlesnakeio/engine/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x17fb7e0, 0xc000320630, 0x16f1700, 0xc000320660, 0xc000354600, 0xc0003261e0, 0xc0004d5830, 0x10786f6, 0x5c709556, 0xc0309ae6d0)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:107 +0xad
github.com/battlesnakeio/engine/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x17fb7e0, 0xc000320630, 0x16f1700, 0xc000320660, 0x6, 0xc00031e640, 0xc0004d58d0, 0x106102a)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9f
github.com/battlesnakeio/engine/controller.loggingInterceptor(0x17fb7e0, 0xc000320630, 0x16f1700, 0xc000320660, 0xc000354600, 0xc0003261e0, 0x1675740, 0x1d5dab8, 0xc0004d5aa0, 0x100be68)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/controller/controller.go:218 +0xb8
github.com/battlesnakeio/engine/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x17fb7e0, 0xc000320630, 0x16f1700, 0xc000320660, 0xc000354600, 0xc000354620, 0x1675740, 0x1d5dab8, 0x1715020, 0xc0002f3540)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x153
github.com/battlesnakeio/engine/controller/pb._Controller_Create_Handler(0x16f5200, 0xc00000b8a0, 0x17fb7e0, 0xc000320630, 0xc000464d90, 0xc0001736b0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/controller/pb/controller.pb.go:1815 +0x158
github.com/battlesnakeio/engine/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003fc000, 0x17fe5c0, 0xc000207080, 0xc0002f3540, 0xc0001737d0, 0x1d32828, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/vendor/google.golang.org/grpc/server.go:923 +0x7b0
github.com/battlesnakeio/engine/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0003fc000, 0x17fe5c0, 0xc000207080, 0xc0002f3540, 0x0)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/vendor/google.golang.org/grpc/server.go:1148 +0x1308
github.com/battlesnakeio/engine/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036690, 0xc0003fc000, 0x17fe5c0, 0xc000207080, 0xc0002f3540)
	/home/travis/gopath/src/github.com/battlesnakeio/engine/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/battlesnakeio/engine/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/travis/gopath/src/github.com/battlesnakeio/engine/vendor/google.golang.org/grpc/server.go:635 **+0xa1**
```

**Comment by dlsteuer** [comment]
This happens when you have more snakes then 8 in the game, and should fall back to random points after the first 8 pre-defined start points are used up.
